version: '3.7'
services:
    postgres:
        image: postgres
        restart: always
        environment:
          POSTGRES_USER: postgres # The PostgreSQL user
          POSTGRES_PASSWORD: 12345 # The PostgreSQL password 
          POSTGRES_DB: default_database # The PostgreSQL default database 
        #logging:
          #options:
            #max-size: 10m
            #max-file: "3"
        ports:
          - '5438:5432'
        volumes: 
          #- ./postgres-data:/var/lib/postgresql/data
          # copy the sql script to create tables
          - ./create-tables.sql:/docker-entrypoint-initdb.d/create-tables.sql